export const practiceDurationOptions = [
  {
    id: "1",
    name: "30 mins /day",
    duration: 30,
  },
  {
    id: "2",
    name: "1 hour /day",
    duration: 60,
  },
  {
    id: "3",
    name: "1 hr 30 mins/day",
    duration: 72,
  },
  {
    id: "4",
    name: "2 hours /day",
    duration: 120,
  },
];

export const questsData = [
  {
    id: "welcome",
    title: "Welcome to Prepme",
    description: "Earned by joining Prepme and completing onboarding",
    isActive: false,
    isCompleted: true,
    percentage: 100,
    category: "onboarding",
    image: "/images/dashboard/badge1.png",
  },
  {
    id: "first-exam",
    title: "First Exam Practice",
    description:
      "Earned by completing your first exam practice and attempting all questions",
    isActive: true,
    isCompleted: false,
    percentage: 0,
    category: "practice",
    image: "/images/dashboard/badge2.png",
  },
  {
    id: "focused-learner",
    title: "Focused Learner",
    description: "Earned by completing a 7-day streak",
    isActive: false,
    isCompleted: false,
    percentage: 0,
    category: "streak",
    image: "/images/dashboard/badge3.png",
  },
  {
    id: "relentless-scholar",
    title: "Relentless Scholar",
    description: "Earned by completing a 30-day streak",
    isActive: false,
    isCompleted: false,
    percentage: 0,
    category: "streak",
    image: "/images/dashboard/badge4.png",
  },
  {
    id: "master-of-persistence",
    title: "Master of Persistence",
    description: "Earned by completing a 100-day streak",
    isActive: false,
    isCompleted: false,
    percentage: 0,
    category: "streak",
    image: "/images/dashboard/badge5.png",
  },
  {
    id: "steadfast-achiever",
    title: "Steadfast Achiever",
    description: "Earned by practicing every day for a month",
    isActive: false,
    isCompleted: false,
    percentage: 0,
    category: "streak",
    image: "/images/dashboard/badge6.png",
  },
  {
    id: "study-buddy",
    title: "Study Buddy",
    description: "Earned by inviting 10+ people",
    isActive: false,
    isCompleted: false,
    percentage: 0,
    category: "social",
    image: "/images/dashboard/badge7.png",
  },
  {
    id: "math-prodigy",
    title: "Math Prodigy",
    description: "Earned by scoring 100% in Maths exams",
    isActive: false,
    isCompleted: false,
    percentage: 0,
    category: "subject",
    image: "/images/dashboard/badge8.png",
  },
  {
    id: "history-buff",
    title: "History Buff",
    description: "Earned by scoring 100% in history exams",
    isActive: false,
    isCompleted: false,
    percentage: 0,
    category: "subject",
    image: "/images/dashboard/badge9.png",
  },
  {
    id: "physics-genius",
    title: "Physics Genius",
    description: "Earned by scoring 100% in Physics exams",
    isActive: false,
    isCompleted: false,
    percentage: 0,
    category: "subject",
    image: "/images/dashboard/badge10.png",
  },
  {
    id: "biology-expert",
    title: "Biology Expert",
    description: "Earned by scoring 100% in Biology exams",
    isActive: false,
    isCompleted: false,
    percentage: 0,
    category: "subject",
    image: "/images/dashboard/badge11.png",
  },
  {
    id: "english-maven",
    title: "English Maven",
    description: "Earned by scoring 100% in English exams",
    isActive: false,
    isCompleted: false,
    percentage: 0,
    category: "subject",
    image: "/images/dashboard/badge12.png",
  },
  {
    id: "civic-champion",
    title: "Civic Champion",
    description: "Earned by scoring 100% in Civic Education exams",
    isActive: false,
    isCompleted: false,
    percentage: 0,
    category: "subject",
    image: "/images/dashboard/badge13.png",
  },
  {
    id: "chemistry-wizard",
    title: "Chemistry Wizard",
    description: "Earned by scoring 100% in Chemistry exams",
    isActive: false,
    isCompleted: false,
    percentage: 0,
    category: "subject",
    image: "/images/dashboard/badge14.png",
  },
  {
    id: "crs-luminary",
    title: "CRS Luminary",
    description: "Earned by scoring 100% in CRS exams",
    isActive: false,
    isCompleted: false,
    percentage: 0,
    category: "subject",
    image: "/images/dashboard/badge15.png",
  },
  {
    id: "science-star",
    title: "Science Star",
    description:
      "Earned by scoring 90%+ in all science subjects (Physics, Biology, Chemistry)",
    isActive: false,
    isCompleted: false,
    percentage: 0,
    category: "achievement",
    image: "/images/dashboard/badge16.png",
  },
  {
    id: "humanities-hero",
    title: "Humanities Hero",
    description:
      "Earned by scoring 90%+ in all humanities (History, Civic Education, CRS, etc.)",
    isActive: false,
    isCompleted: false,
    percentage: 0,
    category: "achievement",
    image: "/images/dashboard/badge17.png",
  },
  {
    id: "grammar-guru",
    title: "Grammar Guru",
    description:
      "Earned by answering all grammar questions correctly in an English exam",
    isActive: false,
    isCompleted: false,
    percentage: 0,
    category: "achievement",
    image: "/images/dashboard/badge18.png",
  },
  {
    id: "formula-master",
    title: "Formula Master",
    description:
      "Earned by solving 10 consecutive Physics or Math questions correctly",
    isActive: false,
    isCompleted: false,
    percentage: 0,
    category: "achievement",
    image: "/images/dashboard/badge19.png",
  },
  {
    id: "ecosystem-explorer",
    title: "Ecosystem Explorer",
    description:
      "Earned by scoring perfect marks in environmental biology questions",
    isActive: false,
    isCompleted: false,
    percentage: 0,
    category: "achievement",
    image: "/images/dashboard/badge20.png",
  },
  {
    id: "the-alchemist",
    title: "The Alchemist",
    description:
      "Earned by correctly solving a chemistry exam involving chemical equations",
    isActive: false,
    isCompleted: false,
    percentage: 0,
    category: "achievement",
    image: "/images/dashboard/badge21.png",
  },
];

export const leaderboardData = [
  { id: "1", username: "Zanny", score: 550 },
  { id: "2", username: "Zanny", score: 510 },
  { id: "3", username: "Zanny", score: 410 },
  { id: "4", username: "Zanny", score: 410 },
  { id: "5", username: "Zanny", score: 410 },
  { id: "6", username: "Zanny", score: 410 },
  { id: "7", username: "Zanny", score: 410 },
  { id: "8", username: "Zanny", score: 410 },
  { id: "9", username: "Zanny", score: 410 },
  { id: "10", username: "Zanny", score: 410 },
  { id: "11", username: "Zanny", score: 410 },
  { id: "12", username: "Zanny", score: 410 },
  { id: "13", username: "Zanny", score: 410 },
  { id: "14", username: "Zanny", score: 410 },
  { id: "15", username: "Zanny", score: 410 },
  { id: "16", username: "Zanny", score: 410 },
  { id: "17", username: "Zanny", score: 410 },
  { id: "18", username: "Zanny", score: 410 },
  { id: "19", username: "Zanny", score: 410 },
  { id: "20", username: "Zanny", score: 410 },
  { id: "21", username: "Sussybabe (You)", score: 0 },
];

export const transactionHistory = [
  {
    id: "1",
    date: "Dec 4, 2024",
    transactions: [
      {
        id: "01",
        transationInfo: {
          title: "Send EDU",
          info: "-20 EDU",
          debit: "-500 XP",
        },
        status: "Confirmed",
      },
      {
        id: "02",
        transationInfo: {
          title: "Convert 200 XP",
          info: "-200 XP",
          debit: "20 EDU",
        },
        status: "Pending",
      },
      {
        id: "03",
        transationInfo: {
          title: "Send EDU",
          info: "-20 EDU",
          debit: "-500 XP",
        },
        status: "Confirmed",
      },
    ],
  },
  {
    id: "2",
    date: "Dec 2, 2024",
    transactions: [
      {
        id: "01",
        transationInfo: {
          title: "Convert 200 XP",
          info: "-20 EDU",
          debit: "-500 XP",
        },
        status: "Confirmed",
      },
      {
        id: "02",
        transationInfo: {
          title: "Convert 200 XP",
          info: "-200 XP",
          debit: "20 EDU",
        },
        status: "Failed",
      },
    ],
  },
];
